---
title: "HW4"
date: 11/6/2024
---

```{r}
library(tidyverse)
library(ggthemes)

```

```{r}
data = read_csv(here::here("airport_pairs.csv"))
head(data)

```

```{r}
print(origin)
```

```{r}
summary(data)
```

```{r}
rdu_routes <- data |>
  filter(origin == "RDU" | dest == "RDU")
```

```{r}
rdu_routes_passengerfilter <- rdu_routes |>
  filter(passengers > 10000)
```

```{r}
rdu_saturation_table <- rdu_routes_passengerfilter |>
  group_by(origin, dest) |>
  summarize(total_passenger = sum(passengers)) |>
  ungroup()
```

```{r}
print(rdu_saturation_table)
```

```{r}
install.packages("tidycensus")

```

```{r}
library(tidycensus)
```

```{r}
census_api_key("863d1963fff9954a0f7bfc13d7ea0dedc02a8034")
```

```{r}
cbsa_population <- get_acs(geography = "metropolitan statistical area/micropolitan statistical area", variables = "B01003_001", year = 2022) |>
  rename(cbsa = GEOID, population = estimate)

head(cbsa_population)

```

```{r}

data <- data |>
  mutate(origin_cbsa = as.character(origin_cbsa),
         dest_cbsa = as.character(dest_cbsa))

origin_population_data <- data |>
  left_join(cbsa_population, by = c("origin_cbsa" = "cbsa")) |>
  rename(origin_pop = population)


destination_population_data <- origin_population_data |>
  left_join(cbsa_population, by = c("dest_cbsa" = "cbsa")) |>
  rename(dest_pop = population)

head(destination_population_data)

```

```{r}
cbsa_summary <- destination_population_data |>
  group_by(origin_cbsa, dest_cbsa, origin_pop, dest_pop, distancemiles) |>
  summarize(total_passengers = sum(passengers), .groups = 'drop') |>
  ungroup()

head(cbsa_summary)
```

```{r}
ggplot(cbsa_summary, aes(x = dest_pop, y = total_passengers)) +
  geom_point() +
  labs(title = "Destination Pop vs Total Pass",
       x = "Destination Pop",
       y= "Total Passengers")
```

```{r}
ggplot(cbsa_summary, aes(x = origin_pop, y = total_passengers)) +
  geom_point() +
  labs(title = "Origin Pop vs Total Pass",
       x = "Origin Pop",
       y = "Total Pass")
```

```{r}
ggplot(cbsa_summary, aes(x = distancemiles, y = total_passengers)) +
  geom_point() +
  labs(title = "Distance vs Total Pass",
       x = "Distance",
       y = "Total Pass")
```

```{r}
#Extra credit attempt

census_api_key("863d1963fff9954a0f7bfc13d7ea0dedc02a8034")


cbsa_age <- get_acs(geography = "metropolitan statistical area/micropolitan statistical area", 
                    variables = "B01002_001", year = 2022) |>
  rename(cbsa = GEOID, median_age = estimate)

head(cbsa_age)

```

```{r}
data <- data |>
  left_join(cbsa_age, by = c("origin_cbsa" = "cbsa")) |>
  rename(origin_age = median_age) |>
  left_join(cbsa_age, by = c("dest_cbsa" = "cbsa")) |>
  rename(dest_age = median_age)
```

```{r}
ggplot(data, aes(x = origin_age, y=passengers)) +
  geom_point() +
  labs(title = "Origin Age vs Total Pass",
       x = "Origin Median Age",
       y = "Total Passengers")
```

```{r}
ggplot(data, aes(x = dest_age, y=passengers)) +
  geom_point() +
  labs(title = "Destination Age vs Total Pass",
       x = "Destination Median Age",
       y = "Total Passengers")
```

```{r}
census_api_key("863d1963fff9954a0f7bfc13d7ea0dedc02a8034")

cbsa_population <- get_acs(geography = "metropolitan statistical area/micropolitan statistical area", variables = "B01003_001", year = 2022) |>
  rename(cbsa = GEOID, population = estimate)

head(cbsa_population)
```

```{r}
data <- data |>
  mutate(origin_cbsa = as.character(origin_cbsa), debt_cbsa = as.character(dest_cbsa))
```

```{r}
data <- data |>
  left_join(cbsa_population, by = c("origin_cbsa" = "cbsa")) |>
  rename(origin_pop = population)
```

```{r}
data <- data |> 
  left_join(cbsa_population, by = c("origin_cbsa" = "cbsa")) |>
  rename(dest_pop = population)

head(data)
```

```{r}
cbsa_summary <- data |>
  group_by(origin_cbsa, dest_cbsa, origin_pop, dest_pop, distancemiles) |>
  summarize(total_passengers = sum(passengers), .groups = 'drop')

head(cbsa_summary)
```

```{r}
passenger_volume_model = lm(total_passengers~origin_pop+dest_pop+distancemiles, data = cbsa_summary)
summary(passenger_volume_model)
```
